services:
  # RabbitMQ - Message Broker
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: challenge-rabbitmq
    hostname: rabbitmq
    networks:
      - challenge-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    
  # API - Sistema de Crédito
  api:
    build:
      context: .
      dockerfile: src/Services/Challenge.Credit.System.Api/Dockerfile
    container_name: challenge-api
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - challenge-network
    restart: unless-stopped

networks:
  challenge-network:
    driver: bridge
    name: challenge-network

volumes:
  rabbitmq_data:
    driver: local
    name: challenge-rabbitmq-data
