services:
  # RabbitMQ - Message Broker
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: challenge-rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - challenge-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    
  # # API
  # api:
  #   build:
  #     context: .
  #     dockerfile: src/Services/Challenge.Credit.System.Api/Dockerfile
  #   container_name: challenge-api
  #   networks:
  #     - challenge-network
  #   restart: unless-stopped

networks:
  challenge-network:
    driver: bridge

volumes:
  rabbitmq_data:
    driver: local
