services:
 rabbitmq:
   environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
   ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management UI
   volumes:
      - rabbitmq_data:/var/lib/rabbitmq
   

 api:
   environment:
     # ASP.NET Core
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      
      # RabbitMQ
      - RabbitMq__HostName=rabbitmq
      - RabbitMq__Port=5672
      - RabbitMq__UserName=guest
      - RabbitMq__Password=guest
      
      # Logging
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - Logging__LogLevel__Challenge.Credit.System=Debug
   ports:
     - "8080:8080"   # HTTP
     - "8081:8081"   # HTTPS (opcional)